Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

# We can either use built-in numpy vander function or create our own

In [10]:
import numpy as np
x = np.array([1, 2, 3, 5])
print(np.vander(x, 3, True))

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]


In [1]:
import numpy as np

def vander_Input(x,N,order):
    X=x.size
    result_array=np.empty((N,X),dtype=int)
    
    if order.upper()=="TRUE":
        for i in range(N):
            power_vector=np.array(np.power(x,i))
            result_array[i]=power_vector
    else:
        for i in range(N-1,-1,-1):
            power_vector=np.array(np.power(x,i))
            result_array[(N-1)-i]=power_vector
    return result_array




N=int(input('Enter N power :'))

print('Enter list of elements like. 1,2,3 :')
input_vector=input()
input_list=list(map(int,input_vector.split(',')))
x=np.array(input_list)
print('Input is :', x)

order=input("Enter 'True' for increasing order of powers else enter 'False' :")

result_array=vander_Input(x,N,order)
print('Vandermonde matrix is :')
print(result_array.T)

Enter N power :3
Enter list of elements like. 1,2,3 :
1,3,6
Input is : [1 3 6]
Enter 'True' for increasing order of powers else enter 'False' :True
Vandermonde matrix is :
[[ 1  1  1]
 [ 1  3  9]
 [ 1  6 36]]
